name: flutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.8 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI / icons
  cupertino_icons: ^1.0.8

  # Networking and environment config
  http: ^1.1.0
  flutter_dotenv: ^5.0.2

  # State management and utils
  provider: ^6.0.5
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env
